"""Lab 6's core generator: LinkML instance data -> SysML v2 textual notation, via plain string
templates -- not a `ToSysml` derive macro (that's real proc-macro engineering, explicitly cut from
this MVP's scope per PRD-0006). A template function produces byte-identical text for a fixed input,
which is all this sprint's demo narrative needs: "one schema edit -> one command -> regenerated
`.sysml`". Two tracks share this one generator, selected by `--track`:

- `digital-thread`: reads `schema/digital_thread_instances.yaml` (Agent/MCPServer/DataSource).
- `grid`: reads `schema/grid_instances.yaml` (Bus/Generator/Line).

Deliberately Part/containment only -- no Port/Flow/connection usage syntax (PRD-0006 scope cut,
matching the sprint plan's own "straight boxes are enough" call). Track B's Line.fromBus/toBus are
plain String attributes holding the referenced part's name, not a real SysML `connect` usage --
named here as the exact substitution a future phase would replace with real reference/connection
syntax once Port/Flow is in scope.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, Final

import yaml

LAB_DIR: Final[Path] = Path(__file__).resolve().parent
SCHEMA_DIR: Final[Path] = LAB_DIR / "schema"
FIXTURES_DIR: Final[Path] = LAB_DIR / "fixtures"
OUTPUT_DIR: Final[Path] = LAB_DIR / "output"

TRACKS: Final[dict[str, dict[str, str]]] = {
    "digital-thread": {
        "instances": "digital_thread_instances.yaml",
        "expected": "expected_digital_thread.sysml",
        "output": "digital_thread.sysml",
    },
    "grid": {
        "instances": "grid_instances.yaml",
        "expected": "expected_grid_topology.sysml",
        "output": "grid_topology.sysml",
    },
}


def _esc(value: str) -> str:
    """Escape a Python string for a SysML v2 double-quoted string literal."""
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render_digital_thread(instances: dict[str, Any]) -> str:
    lines: list[str] = [
        "package DigitalThread {",
        "    // Generated by labs/06-sysml-digital-thread/generate_sysml.py -- do not hand-edit.",
        "    // Source: labs/06-sysml-digital-thread/schema/digital_thread_instances.yaml",
        "",
    ]
    for def_name in ("Agent", "MCPServer", "DataSource"):
        lines += [
            f"    part def {def_name} {{",
            "        attribute source : String;",
            "        attribute refreshCadence : String;",
            "        attribute owner : String;",
            "    }",
            "",
        ]
    lines.append("    part digitalThread {")

    entries: list[tuple[str, str, dict[str, Any]]] = (
        [(e["name"], "Agent", e) for e in instances.get("agents", [])]
        + [(e["name"], "MCPServer", e) for e in instances.get("mcp_servers", [])]
        + [(e["name"], "DataSource", e) for e in instances.get("data_sources", [])]
    )
    for i, (name, type_name, data) in enumerate(entries):
        lines += [
            f"        part {name} : {type_name} {{",
            f'            attribute source = "{_esc(data["source"])}";',
            f'            attribute refreshCadence = "{_esc(data["refresh_cadence"])}";',
            f'            attribute owner = "{_esc(data["owner"])}";',
            "        }",
        ]
        if i != len(entries) - 1:
            lines.append("")
    lines += ["    }", "}"]
    return "\n".join(lines) + "\n"


def render_grid_topology(instances: dict[str, Any]) -> str:
    lines: list[str] = [
        "package GridTopology {",
        "    // Generated by labs/06-sysml-digital-thread/generate_sysml.py -- do not hand-edit.",
        "    // Source: labs/06-sysml-digital-thread/schema/grid_instances.yaml",
        "",
        "    part def Bus {",
        "        attribute source : String;",
        "        attribute voltageKV : Real;",
        "    }",
        "",
        "    part def Generator {",
        "        attribute source : String;",
        "        attribute bus : String;",
        "        attribute ratedMW : Real;",
        "    }",
        "",
        "    part def Line {",
        "        attribute source : String;",
        "        attribute fromBus : String;",
        "        attribute toBus : String;",
        "        attribute kind : String;",
        "        attribute lengthKM : Real;",
        "    }",
        "",
        "    part gridTopology {",
    ]

    buses = instances.get("buses", [])
    generators = instances.get("generators", [])
    grid_lines = instances.get("lines", [])
    total = len(buses) + len(generators) + len(grid_lines)
    i = 0

    for b in buses:
        lines += [
            f"        part {b['name']} : Bus {{",
            f'            attribute source = "{_esc(b["source"])}";',
            f"            attribute voltageKV = {b['voltage_kv']};",
            "        }",
        ]
        i += 1
        if i != total:
            lines.append("")

    for g in generators:
        lines += [
            f"        part {g['name']} : Generator {{",
            f'            attribute source = "{_esc(g["source"])}";',
            f'            attribute bus = "{g["bus"]}";',
            f"            attribute ratedMW = {g['rated_mw']};",
            "        }",
        ]
        i += 1
        if i != total:
            lines.append("")

    for line in grid_lines:
        lines += [
            f"        part {line['name']} : Line {{",
            f'            attribute source = "{_esc(line["source"])}";',
            f'            attribute fromBus = "{line["from_bus"]}";',
            f'            attribute toBus = "{line["to_bus"]}";',
            f'            attribute kind = "{line["kind"]}";',
        ]
        if line.get("length_km") is not None:
            lines.append(f"            attribute lengthKM = {line['length_km']};")
        lines.append("        }")
        i += 1
        if i != total:
            lines.append("")

    lines += ["    }", "}"]
    return "\n".join(lines) + "\n"


RENDERERS: Final[dict[str, Any]] = {
    "digital-thread": render_digital_thread,
    "grid": render_grid_topology,
}


def generate(track: str) -> str:
    cfg = TRACKS[track]
    instances = yaml.safe_load((SCHEMA_DIR / cfg["instances"]).read_text())
    return RENDERERS[track](instances)


def check_step(track: str) -> bool:
    fresh = generate(track)
    expected_path = FIXTURES_DIR / TRACKS[track]["expected"]
    if not expected_path.exists():
        print(f"FAIL: {expected_path} does not exist")
        return False
    expected = expected_path.read_text()
    if fresh == expected:
        print(f"MATCH: generated .sysml for track '{track}' vs {expected_path.name}")
        return True
    print(f"FAIL: generated .sysml for track '{track}' differs from {expected_path.name}")
    return False


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--track", choices=sorted(TRACKS), required=True)
    parser.add_argument("--step", choices=["run", "check"], default="run")
    args = parser.parse_args()

    if args.step == "check":
        sys.exit(0 if check_step(args.track) else 1)

    text = generate(args.track)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = OUTPUT_DIR / TRACKS[args.track]["output"]
    out_path.write_text(text)
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
