//! Repo-relative paths to the real, committed artifacts this lab reads.
//!
//! Resolved from `CARGO_MANIFEST_DIR` (`rust/mission-engine`) so tests work
//! regardless of the working directory the test harness happens to use.

use std::path::{Path, PathBuf};

/// Repository root (two levels up from `rust/mission-engine`).
pub fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("rust/mission-engine has a grandparent directory")
        .to_path_buf()
}

pub fn lab_dir() -> PathBuf {
    repo_root().join("labs/09-cim-gridy-phase1-3-vertical-slice")
}

pub fn fixtures_dir() -> PathBuf {
    lab_dir().join("fixtures")
}

/// Lab 6's real SysML v2 output.
///
/// NOTE this is Lab 6's *committed fixture*, `fixtures/expected_grid_topology.sysml`,
/// not `output/grid_topology.sysml`. `labs/06-sysml-digital-thread/output/` is
/// gitignored (it is regenerated by Lab 6's own pipeline scripts on every run),
/// so it is not guaranteed to exist in a fresh checkout and cannot be what a CI
/// gate reads. The two are byte-identical by construction -- Lab 6's own
/// `generate_sysml.py --step check` asserts exactly that -- so this reads the
/// committed half of that pair.
pub fn lab6_sysml() -> PathBuf {
    repo_root().join("labs/06-sysml-digital-thread/fixtures/expected_grid_topology.sysml")
}

/// Lab 6's LinkML instance data -- the schema side of the Phase 2 cross-check.
pub fn lab6_grid_instances() -> PathBuf {
    repo_root().join("labs/06-sysml-digital-thread/schema/grid_instances.yaml")
}

pub fn episode_fixture() -> PathBuf {
    fixtures_dir().join("episode_observations.jsonl")
}

pub fn mission_fsm_toml() -> PathBuf {
    lab_dir().join("mission_fsm.toml")
}

pub fn mission_fsm_mermaid() -> PathBuf {
    fixtures_dir().join("mission_fsm.mmd")
}

pub fn bus_lookup_json() -> PathBuf {
    fixtures_dir().join("bus_lookup.json")
}

pub fn contingency_candidates_json() -> PathBuf {
    fixtures_dir().join("contingency_candidates.json")
}

/// The live bridge script (`--grid2op-live` only).
pub fn grid2op_bridge_py() -> PathBuf {
    lab_dir().join("grid2op_bridge.py")
}
