use crate::instances::{DigitalThreadInstances, GridInstances, PipelinePhasesInstances};
use crate::numfmt::fmt_real;

fn esc(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

pub fn render_digital_thread(inst: &DigitalThreadInstances) -> String {
    let mut lines: Vec<String> = vec![
        "package DigitalThread {".to_string(),
        "    // Generated by labs/06-sysml-digital-thread/generate_sysml.py -- do not hand-edit.".to_string(),
        "    // Source: labs/06-sysml-digital-thread/schema/digital_thread_instances.yaml".to_string(),
        String::new(),
    ];

    for def_name in ["Agent", "MCPServer", "DataSource"] {
        lines.push(format!("    part def {def_name} {{"));
        lines.push("        attribute source : String;".to_string());
        if def_name == "Agent" {
            lines.push("        attribute uses : String;".to_string());
        }
        lines.push("        attribute refreshCadence : String;".to_string());
        lines.push("        attribute owner : String;".to_string());
        lines.push("    }".to_string());
        lines.push(String::new());
    }
    lines.push("    part digitalThread {".to_string());

    struct Entry<'a> {
        name: &'a str,
        type_name: &'static str,
        source: &'a str,
        uses: Option<&'a str>,
        refresh_cadence: &'a str,
        owner: &'a str,
    }

    let mut entries: Vec<Entry> = Vec::new();
    for a in &inst.agents {
        entries.push(Entry {
            name: &a.name,
            type_name: "Agent",
            source: &a.source,
            uses: a.uses.as_deref(),
            refresh_cadence: &a.refresh_cadence,
            owner: &a.owner,
        });
    }
    for m in &inst.mcp_servers {
        entries.push(Entry {
            name: &m.name,
            type_name: "MCPServer",
            source: &m.source,
            uses: None,
            refresh_cadence: &m.refresh_cadence,
            owner: &m.owner,
        });
    }
    for d in &inst.data_sources {
        entries.push(Entry {
            name: &d.name,
            type_name: "DataSource",
            source: &d.source,
            uses: None,
            refresh_cadence: &d.refresh_cadence,
            owner: &d.owner,
        });
    }

    let total = entries.len();
    for (i, e) in entries.iter().enumerate() {
        lines.push(format!("        part {} : {} {{", e.name, e.type_name));
        lines.push(format!("            attribute source = \"{}\";", esc(e.source)));
        if let Some(uses) = e.uses {
            lines.push(format!("            attribute uses = \"{}\";", esc(uses)));
        }
        lines.push(format!(
            "            attribute refreshCadence = \"{}\";",
            esc(e.refresh_cadence)
        ));
        lines.push(format!("            attribute owner = \"{}\";", esc(e.owner)));
        lines.push("        }".to_string());
        if i != total - 1 {
            lines.push(String::new());
        }
    }
    lines.push("    }".to_string());
    lines.push("}".to_string());
    lines.join("\n") + "\n"
}

pub fn render_grid_topology(inst: &GridInstances) -> String {
    let mut lines: Vec<String> = vec![
        "package GridTopology {".to_string(),
        "    // Generated by labs/06-sysml-digital-thread/generate_sysml.py -- do not hand-edit.".to_string(),
        "    // Source: labs/06-sysml-digital-thread/schema/grid_instances.yaml".to_string(),
        String::new(),
        "    part def Bus {".to_string(),
        "        attribute source : String;".to_string(),
        "        attribute voltageKV : Real;".to_string(),
        "        attribute cimClassUri : String;".to_string(),
        "    }".to_string(),
        String::new(),
        "    part def Generator {".to_string(),
        "        attribute source : String;".to_string(),
        "        attribute bus : String;".to_string(),
        "        attribute ratedMW : Real;".to_string(),
        "        attribute cimClassUri : String;".to_string(),
        "    }".to_string(),
        String::new(),
        "    part def Line {".to_string(),
        "        attribute source : String;".to_string(),
        "        attribute fromBus : String;".to_string(),
        "        attribute toBus : String;".to_string(),
        "        attribute kind : String;".to_string(),
        "        attribute lengthKM : Real;".to_string(),
        "        attribute cimClassUri : String;".to_string(),
        "    }".to_string(),
        String::new(),
        "    part gridTopology {".to_string(),
    ];

    let total = inst.buses.len() + inst.generators.len() + inst.lines.len();
    let mut i = 0;

    for b in &inst.buses {
        lines.push(format!("        part {} : Bus {{", b.name));
        lines.push(format!("            attribute source = \"{}\";", esc(&b.source)));
        lines.push(format!("            attribute voltageKV = {};", fmt_real(b.voltage_kv)));
        lines.push(format!(
            "            attribute cimClassUri = \"{}\";",
            esc(&b.cim_class_uri)
        ));
        lines.push("        }".to_string());
        i += 1;
        if i != total {
            lines.push(String::new());
        }
    }

    for g in &inst.generators {
        lines.push(format!("        part {} : Generator {{", g.name));
        lines.push(format!("            attribute source = \"{}\";", esc(&g.source)));
        lines.push(format!("            attribute bus = \"{}\";", g.bus));
        lines.push(format!("            attribute ratedMW = {};", fmt_real(g.rated_mw)));
        lines.push(format!(
            "            attribute cimClassUri = \"{}\";",
            esc(&g.cim_class_uri)
        ));
        lines.push("        }".to_string());
        i += 1;
        if i != total {
            lines.push(String::new());
        }
    }

    for l in &inst.lines {
        lines.push(format!("        part {} : Line {{", l.name));
        lines.push(format!("            attribute source = \"{}\";", esc(&l.source)));
        lines.push(format!("            attribute fromBus = \"{}\";", l.from_bus));
        lines.push(format!("            attribute toBus = \"{}\";", l.to_bus));
        lines.push(format!("            attribute kind = \"{}\";", l.kind));
        if let Some(length_km) = l.length_km {
            lines.push(format!("            attribute lengthKM = {};", fmt_real(length_km)));
        }
        lines.push(format!(
            "            attribute cimClassUri = \"{}\";",
            esc(&l.cim_class_uri)
        ));
        lines.push("        }".to_string());
        i += 1;
        if i != total {
            lines.push(String::new());
        }
    }

    lines.push("    }".to_string());
    lines.push("}".to_string());
    lines.join("\n") + "\n"
}

pub fn render_pipeline_phases(inst: &PipelinePhasesInstances) -> String {
    let mut lines: Vec<String> = vec![
        "package PipelinePhases {".to_string(),
        "    // Generated by labs/06-sysml-digital-thread/generate_sysml.py -- do not hand-edit.".to_string(),
        "    // Source: labs/06-sysml-digital-thread/schema/pipeline_phases_instances.yaml".to_string(),
        String::new(),
        "    part def Phase {".to_string(),
        "        attribute source : String;".to_string(),
        "        attribute role : String;".to_string(),
        "        attribute next : String;".to_string(),
        "    }".to_string(),
        String::new(),
        "    part pipelinePhases {".to_string(),
    ];

    let total = inst.phases.len();
    for (i, p) in inst.phases.iter().enumerate() {
        lines.push(format!("        part {} : Phase {{", p.name));
        lines.push(format!("            attribute source = \"{}\";", esc(&p.source)));
        lines.push(format!("            attribute role = \"{}\";", esc(&p.role)));
        if let Some(next) = &p.next {
            lines.push(format!("            attribute next = \"{next}\";"));
        }
        lines.push("        }".to_string());
        if i != total - 1 {
            lines.push(String::new());
        }
    }

    lines.push("    }".to_string());
    lines.push("}".to_string());
    lines.join("\n") + "\n"
}
